# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Vzl8bs3Fmrw9YZCZxaS0zn0JMmCZPl_
"""

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time

# Setup Chrome options
chrome_options = Options()
chrome_options.add_argument("--headless")  # Run without GUI
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")

# Start driver
driver = webdriver.Chrome(options=chrome_options)

driver.get("https://www.google.com")

time.sleep(2)

print("Title:", driver.title)

driver.quit()